### PR TITLE
Percent

### PR DESCRIPTION
**Pull request by njam3**
@mikkoh The only caveat with this is that it must be from a percent to a percent (in the states file). It can not go between percent and number.

### CODE REVIEW

**Comment by mikkoh** [comment]
Sooo this is pretty well how I was gonna implement it. One issue I had was what if you did something like this:

```
{
  start: {
    ui: {
      left: 10
    }
  },

  end: {
    ui: {
      left: '100%'
    }
  }
}
```

I also wonder if there are more performant ways of doing this than using `parseFloat` during every frame of execution.

**Comment by njam3** [comment]
@mikkoh I tried it without parseFloat and got some very weird results going from 100 to 0 without parseFloat caused it to go from 0 to -100. I'm not sure if there is a solution to going from a static number to a percent number, but i don't think its need, we could have a warning and interpolate the number as 10%

**Comment by njam3** [comment]
@mikkoh I changed parseFloat to *1 as its apparently more performant: http://phrogz.net/js/string_to_number.html

**Comment by njam3** [comment]
@mikkoh Actually, i updated it again to be Number() as that seems the quickest and the most readable.

**Pull request merged**
