### PR TITLE
Add a basic TypeScript Declaration File

### PR DESCRIPTION
**Pull request by neo**
Add basic TypeScript support.

### CODE REVIEW

**Comment by mikkoh** [comment]
I don't think this should live in `f1` if you want I suggest making a module `f1-typescript` that would just have `f1` as a peer dependency.

But I also feel there must be a way to consume CommonJS modules in Typescript which might be a better route.

**Review by mikkoh — CHANGES_REQUESTED** [review]
I don't think this should live in f1 if you want I suggest making a module f1-typescript that would just have f1 as a peer dependency.

But I also feel there must be a way to consume CommonJS modules in Typescript which might be a better route.

**Comment by neo** [comment]
Added it [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/f1)

**Comment by neo** [comment]
Maybe I could add it to the README? @mikkoh @njam3

**Comment by neo** [comment]
I think it's worth mentioning that it is recommended to add types with the library: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0#create-a-new-package

**Pull request closed without merging**
